# Cloud Build configuration per deploy automatico su Cloud Run
steps:
  # Build dell'immagine Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/nestjs-microservice:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/nestjs-microservice:latest'
      - '.'

  # Push dell'immagine su Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/nestjs-microservice:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/nestjs-microservice:latest'

  # Deploy su Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nestjs-microservice'
      - '--image'
      - 'gcr.io/$PROJECT_ID/nestjs-microservice:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'

images:
  - 'gcr.io/$PROJECT_ID/nestjs-microservice:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/nestjs-microservice:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: 1200s
